# Generated by Django 6.0.6 on 2026-08-11 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version_number_major', models.IntegerField(default=1)),
                ('version_number_minor', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='future_version', to='task_management.category')),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to='task_management.category')),
                ('superiors_additional', models.ManyToManyField(blank=True, related_name='subordinates_additional', to='task_management.category')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version_number_major', models.IntegerField(default=1)),
                ('version_number_minor', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='future_version', to='task_management.action')),
                ('additional_categories', models.ManyToManyField(blank=True, related_name='actions_additional', to='task_management.category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='task_management.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version_number_major', models.IntegerField(default=1)),
                ('version_number_minor', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='future_version', to='task_management.tag')),
                ('superiors', models.ManyToManyField(blank=True, related_name='subordinates', to='task_management.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version_number_major', models.IntegerField(default=1)),
                ('version_number_minor', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('actions', models.ManyToManyField(to='task_management.action')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='future_version', to='task_management.activity')),
                ('additional_categories', models.ManyToManyField(blank=True, related_name='activities_additional', to='task_management.category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='task_management.category')),
                ('tags', models.ManyToManyField(blank=True, to='task_management.tag')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(blank=True, to='task_management.tag'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version_number_major', models.IntegerField(default=1)),
                ('version_number_minor', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='NOT_STARTED', max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_management.activity')),
                ('additional_actions', models.ManyToManyField(blank=True, to='task_management.action')),
                ('additional_categories', models.ManyToManyField(blank=True, related_name='tasks_additional', to='task_management.category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_management.category')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='future_version', to='task_management.task')),
                ('tags', models.ManyToManyField(blank=True, to='task_management.tag')),
            ],
        ),
    ]
