# Generated by Django 6.0.6 on 2026-08-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='additional_categories',
            new_name='categories_additional',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='additional_categories',
            new_name='categories_additional',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='additional_categories',
            new_name='categories_additional',
        ),
    ]
