# Generated by Django 6.0.6 on 2026-08-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_rename_additional_categories_action_categories_additional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_root', True), ('superior__isnull', True)), models.Q(('is_root', False), ('superior__isnull', False)), _connector='OR'), name='category_root_or_has_superior', violation_error_message='A non-root category must have a superior.'),
        ),
    ]
