# Generated by Django 6.0.6 on 2026-08-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_category_is_root_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='superior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to='task_management.category'),
        ),
    ]
