# Generated by Django 6.0.6 on 2026-08-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_alter_category_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to='task_management.category'),
        ),
    ]
