services:
  backend:
    build: ./tms_backend
    container_name: backend-container
    ports:
      - "${BACKEND_PORT_NUMBER}:${BACKEND_PORT_NUMBER}"
    volumes:
      - ./tms_backend:/app
    env_file:
      - ./tms_backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - ${POSTGRES_HOST}

  database:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  frontend:
    build: ./tms_frontend
    container_name: frontend-container
    ports:
      - "${FRONTEND_PORT_NUMBER}:${FRONTEND_PORT_NUMBER}"
    volumes:
      - ./tms_frontend:/app
      - /app/node_modules
    env_file:
      - ./tms_frontend/.env

volumes:
  postgres_data: